### ISSUE TITLE
Screen flickers on Windows

### ISSUE THREAD

**Issue by cflip** [h5p9sl/sriv#1] opened 2020-09-09 02:48 UTC
When i run the program it runs. But there is a black flicker for some odd reason.

**Comment by h5p9sl** [comment] 2020-09-18 02:24
Bug fixed in a8e416a8ae5480f10ee95d048bd4da785c171c49
The bug was caused by **very excessive** buffer swapping.

**Closed by h5p9sl** 2020-09-18 02:24 UTC
Labels: bug
